"""changed nullable to not null

Revision ID: cc51e3415b8c
Revises: c01b5e18117f
Create Date: 2026-06-08 11:23:56.796300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc51e3415b8c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hints')
    op.drop_table('doubts')
    op.drop_table('user_details')
    op.drop_table('steps')
    op.drop_table('questions')
    op.drop_table('solutions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solutions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('doubt_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doubt_id'], ['doubts.id'], name=op.f('solutions_doubt_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('solutions_pkey')),
    sa.UniqueConstraint('doubt_id', name=op.f('solutions_doubt_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('questions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('doubt_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('class_name', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doubt_id'], ['doubts.id'], name=op.f('questions_doubt_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('questions_pkey')),
    sa.UniqueConstraint('doubt_id', name=op.f('questions_doubt_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('steps',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('solution_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('step_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], name=op.f('steps_solution_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('steps_pkey'))
    )
    op.create_table('user_details',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('available_free_doubts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_details_pkey')),
    sa.UniqueConstraint('email', name=op.f('user_details_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('doubts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_details.id'], name=op.f('doubts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('doubts_pkey'))
    )
    op.create_table('hints',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('solution_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('hint_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], name=op.f('hints_solution_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('hints_pkey'))
    )
    # ### end Alembic commands ###
